// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2YjKKoHioniWQBZKk92gJyPow7NVMGxk',
    appId: '1:970935403304:web:b1ae3d3f54df6e1d96461d',
    messagingSenderId: '970935403304',
    projectId: 'phone-auth-app-f7254',
    authDomain: 'phone-auth-app-f7254.firebaseapp.com',
    storageBucket: 'phone-auth-app-f7254.appspot.com',
    measurementId: 'G-2H8DSKLPNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GLhWatLFzCaheBerfcCzNKODvY7V6eA',
    appId: '1:970935403304:android:8f95a08340a8eaa196461d',
    messagingSenderId: '970935403304',
    projectId: 'phone-auth-app-f7254',
    storageBucket: 'phone-auth-app-f7254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3olUyNQiDQsbUFz53iwYAF0SwzkUML0',
    appId: '1:970935403304:ios:5b6493ebabbb7d2e96461d',
    messagingSenderId: '970935403304',
    projectId: 'phone-auth-app-f7254',
    storageBucket: 'phone-auth-app-f7254.appspot.com',
    iosBundleId: 'com.micro.numVerify',
  );
}
